### PR TITLE
Playing with tables in html

### PR DESCRIPTION
**Pull request by deeamon128**
work in progress as I am trying to figure out how to create the style in a different way for each of the tables.

### CODE REVIEW

**Review by QuintyHH — CHANGES_REQUESTED** [review]
Please refactor according to our conversation on Discord :)

**Review by QuintyHH — APPROVED** [review]
Parfait 💯

**Comment by deeamon128** [comment]
> Parfait 💯

Many thanks for your help, Razvan! 💯

**Review by RalucaRbc — APPROVED** [review]

**Review by Adrian01C — APPROVED** [review]
nice

**Review by QuintyHH — APPROVED** [review]

**Review by psyhedeliq — APPROVED** [review]

**Review by BogdanNegura — APPROVED** [review]
👍

**Pull request merged**
