### PR TITLE
fix dark theme and mobile version

### PR DESCRIPTION
**Pull request by simonamarcu2**

### CODE REVIEW

**Review by Adrian01C — APPROVED** [review]
Nicee

**Review by NicolaePaulGeambazu — APPROVED** [review]

**Comment by NicolaePaulGeambazu** [comment]
Good work

**Review by Nicolleta1981 — APPROVED** [review]
I am new so no ideea about svg i just looked a little on css and :
-notices some lines in comments, 161-166 are exactly your comment 170-175, 145-150 comment. 
-h1 and h2 maybe if they would have text-align center you would not need make display block for them. on h1 you put style normal but browser usually chose that without specify
-margin defined by  16px 0(px no need) that means first value top/bottom and value second right/left and after i saw left 7px and top 122px. I tried on w3 schooles and if you put margin i think is useless your top and left. But maybe i am wrong.
Is apreciated that you had no peacking so good job. Probably are some small changes that you could do but if looks like Marian great job.

**Comment by simonamarcu2** [comment]
> I am new so no ideea about svg i just looked a little on css and :
> -notices some lines in comments, 161-166 are exactly your comment 170-175, 145-150 comment.
> -h1 and h2 maybe if they would have text-align center you would not need make display block for them. on h1 you put style normal but browser usually chose that without specify
> -margin defined by 16px 0(px no need) that means first value top/bottom and value second right/left and after i saw left 7px and top 122px. I tried on w3 schooles and if you put margin i think is useless your top and left. But maybe i am wrong.
> Is apreciated that you had no peacking so good job. Probably are some small changes that you could do but if looks like Marian great job.

**Review by marianzburlea — APPROVED** [review]
💯

**Pull request merged**
