### PR TITLE
2021 03 18 vasilemaftita thursday coding

### PR DESCRIPTION
**Pull request by vasilemaftita**

### CODE REVIEW

**Review by M00N89 — COMMENTED** [review]
bravo Vasile continua asa 👍🏻

**Review by BogdanNegura — APPROVED** [review]
👍 good practice, keep going Vasile!

**Review by robertoalx — APPROVED** [review]
Good Job Vasile, you refactor all the files 💯

**Review by RalucaRbc — APPROVED** [review]
👍

**Review by marianzburlea — APPROVED** [review]
💯

**Pull request merged**
