### PR TITLE
added image map and background image

### PR DESCRIPTION
**Pull request by simonamarcu2**

### CODE REVIEW

**Review by marianzburlea — APPROVED** [review]
💯

**Review by vasilemaftita — APPROVED** [review]
Nice; Work!

**Review by adelacecilia — APPROVED** [review]
Nice! Keep it up! 👍🏻

**Review by QuintyHH — APPROVED** [review]
:100: Nice use of maps!

**Review by robertoalx — APPROVED** [review]
Looking good 💯

**Pull request merged**
