### PR TITLE
2021 03 20 deeamon128 wannalearncss

### PR DESCRIPTION
**Pull request by deeamon128**

### CODE REVIEW

**Review by Constantin-Matei — APPROVED** [review]

**Comment by marianzburlea** [comment]
next time name your branch to be more readable, like: `2021-03-20-deeamon128-wanna-learn-css`

**Review by marianzburlea — COMMENTED** [review]
next time name your branch to be more readable, like: `2021-03-20-deeamon128-wanna-learn-css`

**Review by samuray90 — APPROVED** [review]

**Review by andreimaff — APPROVED** [review]

**Review by Constantin-Matei — APPROVED** [review]
Empty line :)

**Comment by deeamon128** [comment]
> Empty line :)

I have empty lines in both files, HTML and CSS, in the last commit I have uploaded.

**Review by vasilemaftita — COMMENTED** [review]
Nice

**Pull request merged**
