### PR TITLE
 2021 03 14 sunday coding

### PR DESCRIPTION
**Pull request by vasilemaftita**

### CODE REVIEW

**Review by M00N89 — APPROVED** [review]

**Review by M00N89 — APPROVED** [review]

**Review by robertoalx — APPROVED** [review]

**Review by samuray90 — APPROVED** [review]

**Review by marianzburlea — CHANGES_REQUESTED** [review]
image

**Review by Constantin-Matei — APPROVED** [review]
:)

**Review by psyhedeliq — APPROVED** [review]
Well done @vasilemaftita ! 🚀 🤘

**Review by marianzburlea — APPROVED** [review]
💯

**Pull request merged**
