### PR TITLE
WIP: 2021 04 19 deeamon128 music player

### PR DESCRIPTION
**Pull request by deeamon128**

### CODE REVIEW

**Review by Constantin-Matei — APPROVED** [review]
💯 Nice work.

**Review by vasilemaftita — APPROVED** [review]
Nice.

**Review by biggicode — APPROVED** [review]
💯

**Review by psyhedeliq — APPROVED** [review]

**Review by simonamarcu2 — COMMENTED** [review]
Fab work!

**Review by RalucaRbc — APPROVED** [review]
👍 niiice

**Pull request merged**
