### PR TITLE
2021 03 18 adelacecilia practice coding number two

### PR DESCRIPTION
**Pull request by adelacecilia**

### CODE REVIEW

**Review by robertoalx — APPROVED** [review]
Good job!

**Review by andreimaff — APPROVED** [review]
nice 👍🏼

**Review by QuintyHH — APPROVED** [review]
Awesome Pawsome

**Review by biggicode — APPROVED** [review]

**Review by RalucaRbc — APPROVED** [review]
Niiiice 💯 🚀

**Review by psyhedeliq — APPROVED** [review]

**Review by marianzburlea — APPROVED** [review]
I like this clean style 💯

**Pull request merged**
